version: 2

multi-ecosystem-groups:
  uv-lock:
    schedule:
      interval: "monthly"
      # interval: "cron"
      # cronjob: "0 6 1 */3 *"
    commit-message:
      prefix: "🤖 Dependabot Chore:"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "uv-lock"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "uv-lock"

  - package-ecosystem: "pre-commit"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "uv-lock"
