# https://autofix.ci/setup

name: autofix.ci
on:
  workflow_call:
  pull_request:
  # Local prek is good enough for "main" branch 
  # push:
  #   branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # Use uv to ensure we have the same ruff version in CI and locally.
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      # Fix lint errors
      - run: uv run ruff check --fix-only .
      # Format code
      - run: uv run ruff format .

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
